from Functionprograms.operations import *
num1=int(input("Enter the first number "))
num2=int(input("Enter the second number "))
data1=add(num1,num2)
data2=sub(num1,num2)
data3=mult(num1,num2)
data4=div(num1,num2)
print(data1)
print(data2)
print(data3)
print(data4)
