import Functionprograms.operations
num1=int(input("Enter the first number "))
num2=int(input("Enter the second number "))
add=Functionprograms.operations.add(num1,num2)
sub=Functionprograms.operations.sub(num1,num2)
mult=Functionprograms.operations.mult(num1,num2)
div=Functionprograms.operations.div(num1,num2)
print(add)
print(sub)
print(mult)
print(div)